services:
  database:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: app
      POSTGRES_DB: app
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - '9080:8080'
